INSERT INTO lieferant (lieferantenname, telefon, email) VALUES
                                                            ('Bäckerei Müller GmbH',                         '+49 30 1234567',             'info@baeckerei-mueller.de'),
                                                            ('Dr. Oetker Lebensmittel AG',                   '+49 521 5450',               'contact@oetker.de'),
                                                            ('Haribo GmbH & Co. KG',                         '+49 221 5985-0',             'service@haribo.com'),
                                                            ('Bahlsen GmbH & Co. KG',                        '+49 511 97080',              'info@bahlsen.de'),
                                                            ('Kräuterland GmbH',                             '+49 89 123456',              'verkauf@kraeuterland.de'),
                                                            ('Feinkost Käfer GmbH',                          '+49 89 925130',              'kundendienst@feinkost-kaefer.de'),
                                                            ('Schwartau GmbH & Co. KGaA',                    '+49 4106 8010',              'info@schwartau.de'),
                                                            ('Hengstenberg GmbH & Co. KG',                   '+49 711 17280',              'info@hengstenberg.de'),
                                                            ('Rapsöl Erle GmbH',                             '+49 234 7890123',            'sales@rapsoel-erle.de'),
                                                            ('Weihenstephan GmbH & Co. KG',                  '+49 8161 3890',              'kontakt@weihenstephan.de'),
                                                            ('Südzucker AG',                                 '+49 6021 3010',              'info@suedzucker.de'),
                                                            ('K+S Minerals and Agriculture GmbH',            '+49 561 9301',               'kontakt@ks.de'),
                                                            ('Melitta Group',                                '+49 521 9740',               'office@melitta.de'),
                                                            ('Zentis GmbH & Co. KG',                         '+49 69 30510',               'info@zentis.de'),
                                                            ('Develey Senf & Feinkost GmbH',                 '+49 89 33000',               'service@develey.de'),
                                                            ('Löwensenf GmbH',                               '+49 721 45150',              'info@loewensenf.de'),
                                                            ('Schokoladenfabrik Ritter Sport GmbH & Co. KG', '+49 7071 5000',              'office@ritter-sport.de'),
                                                            ('Wernsing Feinkost GmbH',                       '+49 4446 710',               'sales@wernsing.com'),
                                                            ('Ajinomoto Eurolysine GmbH',                    '+49 561 95230',              'contact@ajinomoto-eurolysine.com'),
                                                            ('Goldpuder GmbH',                               '+49 221 888000',             'team@goldpuder.de');


INSERT INTO lieferantadresse (lieferantennr, ort, strasse, hausnr, plz) VALUES
                                                                              (1,  'Berlin',            'Bäckerstraße',        12, 10115),
                                                                              (2,  'Bielefeld',         'Oetkerstraße',         1,  33604),
                                                                              (3,  'Bonn',              'Goldbärenweg',        23, 53111),
                                                                              (4,  'Hannover',          'Bahlsenallee',        5,  30159),
                                                                              (5,  'München',           'Kräuterweg',          77, 80331),
                                                                              (6,  'München',           'Feinkoststraße',      9,  80333),
                                                                              (7,  'Bad Schwartau',     'Marmeladenweg',       18, 23611),
                                                                              (8,  'Esslingen',         'Essigstraße',         2,  73728),
                                                                              (9,  'Bochum',            'Ölstraße',            45, 44787),
                                                                              (10, 'Freising',          'Milchweg',            3,  85356),
                                                                              (11, 'Mannheim',          'Zuckerallee',         15, 68159),
                                                                              (12, 'Kassel',            'Mineralweg',          5,  34117),
                                                                              (13, 'Minden',            'Kaffeeweg',           8,  32423),
                                                                              (14, 'Aachen',            'Fruchtstraße',        30, 52062),
                                                                              (15, 'Unterhaching',      'Senfstraße',          4,  82008),
                                                                              (16, 'Düsseldorf',        'Löwenstraße',         10, 40210),
                                                                              (17, 'Waldenbuch',        'Schokoladenweg',      1,  71111),
                                                                              (18, 'Addrup',            'Feinkoststraße',      6,  49632),
                                                                              (19, 'Kassel',            'Aminosäurenweg',      14, 34121),
                                                                              (20, 'Köln',              'Mehlstraße',          11, 50667);
