INSERT INTO kunde (nachname, vorname, geburtsdatum, telefon, email) VALUES
                                                                        ('Müller',        'Max',       '1985-05-12',   '+49 30 1234567',       'max.mueller@example.com'),
                                                                        ('Schmidt',       'Anna',      '1990-11-22',   '+49 89 2345678',       'anna.schmidt@example.com'),
                                                                        ('Schneider',     'Peter',     '1978-03-08',   '+49 40 3456789',       'peter.schneider@example.com'),
                                                                        ('Fischer',       'Julia',     '1995-07-30',   '+49 171 4567890',      'julia.fischer@example.com'),
                                                                        ('Weber',         'Lukas',     '1980-02-15',   '+49 30 5678901',       'lukas.weber@example.com'),
                                                                        ('Wagner',        'Clara',     '1992-09-25',   '+49 89 6789012',       'clara.wagner@example.com'),
                                                                        ('Becker',        'Paul',      '1988-12-01',   '+49 40 7890123',       'paul.becker@example.com'),
                                                                        ('Hoffmann',      'Eva',       '1983-01-17',   '+49 171 8901234',      'eva.hoffmann@example.com'),
                                                                        ('Schulz',        'Johannes',  '1996-04-04',   '+49 30 9012345',       'johannes.schulz@example.com'),
                                                                        ('Zimmermann',    'Sophia',    '1987-10-30',   '+49 89 2345679',       'sophia.zimmermann@example.com'),
                                                                        ('Hartmann',      'David',     '1993-08-19',   '+49 40 3456780',       'david.hartmann@example.com'),
                                                                        ('Schröder',      'Maria',     '1981-05-03',   '+49 171 4567891',      'maria.schroeder@example.com'),
                                                                        ('Klein',         'Jan',       '1975-06-20',   '+49 30 1234568',       'jan.klein@example.com'),
                                                                        ('Wolf',          'Laura',     '1998-01-10',   '+49 89 3456789',       'laura.wolf@example.com'),
                                                                        ('Neumann',       'Maximilian','1989-11-17',   '+49 40 5678902',       'maximilian.neumann@example.com'),
                                                                        ('Jäger',         'Lena',      '1992-05-05',   '+49 171 6789012',      'lena.jaeger@example.com'),
                                                                        ('Peters',        'Felix',     '1980-09-22',   '+49 30 7890124',       'felix.peters@example.com'),
                                                                        ('Meyer',         'Sarah',     '1984-02-13',   '+49 89 8901234',       'sarah.meyer@example.com'),
                                                                        ('Richter',       'Tim',       '1994-12-02',   '+49 40 1234567',       'tim.richter@example.com'),
                                                                        ('Kramer',        'Emma',      '1990-07-17',   '+49 171 2345678',      'emma.kramer@example.com');


INSERT INTO kundeadresse (kundennnr, stadt, strasse, hausnr, plz) VALUES
                                                                      (1,  'Berlin',           'Unter den Linden',       10, 10115),
                                                                      (2,  'München',          'Maximilianstraße',        5,  80331),
                                                                      (3,  'Hamburg',          'Mönckebergstraße',        20, 20095),
                                                                      (4,  'Köln',             'Hohenzollernring',        15, 50667),
                                                                      (5,  'Stuttgart',        'Königstraße',             25, 70173),
                                                                      (6,  'Frankfurt',        'Zeil',                    8,  60311),
                                                                      (7,  'Düsseldorf',       'Königsallee',             3,  40210),
                                                                      (8,  'Dortmund',         'Westenhellweg',           18, 44135),
                                                                      (9,  'Essen',            'Altendorfer Strasse',     12, 45326),
                                                                      (10, 'Leipzig',          'Grimmaische Strasse',      7,  04109),
                                                                      (11, 'Bremen',           'Osterdeich',              11, 28195),
                                                                      (12, 'Hannover',         'Georgstraße',             4,  30159),
                                                                      (13, 'Dresden',          'Prager Strasse',          9,  01067),
                                                                      (14, 'Nürnberg',         'Königstraße',             6,  90402),
                                                                      (15, 'Münster',          'Steinfurter Strasse',     21, 48143),
                                                                      (16, 'Aachen',           'Adalbertstraße',          3,  52062),
                                                                      (17, 'Bielefeld',        'Altstädter Ring',         22, 33602),
                                                                      (18, 'Kassel',           'Königstraße',             8,  34117),
                                                                      (19, 'Würzburg',         'Röntgenstraße',           14, 97070),
                                                                      (20, 'Freiburg',         'Kaiser-Joseph-Straße',    17, 79098);
